spring.security.user.name= user
spring.security.user.password= Pwd1
server.port=9095


spring.application.name=Admin
spring.data.mongodb.uri=mongodb://localhost:27017/challangers

logging.level.org.springframework.security=DEBUG


#server.error.whitelabel.enabled= false